import { Router } from "express";
import healthRouter from "./health.js";
import ordersRouter from "./orders.js";
import contactRouter from "./contact.js";
import productsRouter from "./products.js";
import colorsRouter from "./colors.js";
import servicesRouter from "./services.js";
import capacityRouter from "./capacity.js";
import waitlistRouter from "./waitlist.js";
import notifyRouter from "./notify.js";
import newsletterRouter from "./newsletter.js";
import checkoutRouter from "./checkout.js";
import cartRemindersRouter from "./cart-reminders.js";
import shopOrdersRouter from "./shop-orders.js";
import appointmentsRouter from "./appointments.js";
import accountRouter from "./account.js";
import studioRouter from "./studio.js";
import reviewsRouter from "./reviews.js";
import portfolioRouter from "./portfolio.js";

const router = Router();

router.use(healthRouter);
router.use(ordersRouter);
router.use(contactRouter);
router.use(productsRouter);
router.use(colorsRouter);
router.use(servicesRouter);
router.use(capacityRouter);
router.use(waitlistRouter);
router.use(notifyRouter);
router.use(newsletterRouter);
router.use(checkoutRouter);
router.use(cartRemindersRouter);
router.use(shopOrdersRouter);
router.use(appointmentsRouter);
router.use(accountRouter);
router.use(studioRouter);
router.use(reviewsRouter);
router.use(portfolioRouter);

export default router;
